### ISSUE TITLE
Feature: Explicitly name profiles

### ISSUE THREAD

**Issue by quinnypig** [assetnote/ghostbuster#2]
It would be great to be able to explicitly give a `--profile` or `--profiles` argument to only target a selected account; some of us have an awful lot of accounts in our config.

**Comment by infosec-au** [comment]
Hi @QuinnyPig

I have released a new version which allows you to specify a specific profile to run ghostbuster against via the `--profile` flag. 

In the scenario that you want to run on all profiles except for some, you can also use the `--exclude` flag, containing a comma delimited list of profiles you do not want ghostbuster to run on.

Thanks for the feedback.
