### ISSUE TITLE
Adding additional credentials for e.g. staging environment

### ISSUE THREAD

**Issue by thistehneisen** [assetnote/ghostbuster#5]
Hello,

How is it possible to add additional credentials in .aws/credentials:
```
[default]
aws_access_key_id = AKIAIII...
aws_secret_access_key = faAaAaA...
```

For different instance? Should just adding e.g. [staging] with their credentials suffice?

**Comment by infosec-au** [comment]
Yeah! You can just add a new block with a different profile name. The tool should pick up all of the profiles.
